/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Cats: typeof import('./components/Cats.vue')['default']
    Overview: typeof import('./components/Overview.vue')['default']
    ProjectBasic: typeof import('./components/ProjectBasic.vue')['default']
    ProjectCell: typeof import('./components/ProjectCell.vue')['default']
    ProjectDialog: typeof import('./components/ProjectDialog.vue')['default']
    ProjectsGrid: typeof import('./components/ProjectsGrid.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
