/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    ProjectBasic: typeof import('./components/ProjectBasic.vue')['default']
    ProjectCell: typeof import('./components/ProjectCell.vue')['default']
    ProjectFlexposure: typeof import('./components/ProjectFlexposure.vue')['default']
    ProjectHobby: typeof import('./components/ProjectHobby.vue')['default']
    ProjectNurtio: typeof import('./components/ProjectNurtio.vue')['default']
    ProjectOBG: typeof import('./components/ProjectOBG.vue')['default']
    ProjectPriva: typeof import('./components/ProjectPriva.vue')['default']
    ProjectsGrid: typeof import('./components/ProjectsGrid.vue')['default']
    ProjectSioux: typeof import('./components/ProjectSioux.vue')['default']
    ProjectSiqura: typeof import('./components/ProjectSiqura.vue')['default']
    ProjectSupershift: typeof import('./components/ProjectSupershift.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
